### ISSUE TITLE
Is 5.2.8. missing a title?

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/the-spec#1]
Right now it states:

```
5.2.8. d
```

I cannot extract a title. `data` or `defined attributes` seemed appropriate, but I cannot be certain.

**Comment by dmolsen** [comment]
I'll add an explanation inside a parens there. The name of the var in the PHP version is… well, `d`. The other listed items also match the var names in the PHP version. Just to make it easy to compare.

**Comment by bmuenzenmeyer** [comment]
Sounds good. I am behind the times on PL-PHP it seems :)

**Comment by dmolsen** [comment]
`d` has been around from the beginning I think. If it's an abbreviated var name (e.g. `ie`) it's from the first iteration before I really thought about properly naming things ;)

Added an explanation. It'll be clearer in the final version.
