### ISSUE TITLE
Spec Update

### ISSUE THREAD

**Issue by dmolsen** [pattern-lab/the-spec#10]
@pattern-lab/port-maintainers ,

I want to quickly touch base regarding the current status of the spec. I haven't touched it for a bit as I work through a number of issues in the PHP edition of Pattern Lab. Basically, before I dove to deep into the spec I wanted to make sure that some of the new features worked and what effect that might have here. I'm not completely done but I've made a ton of progress as seen in the difference between the core of Pattern Lab [in the master branch](https://github.com/pattern-lab/patternlab-php/tree/master/core/lib/PatternLab) and [in the dev branch](https://github.com/pattern-lab/patternlab-php/tree/dev/core/lib/PatternLab).

Some highlights:
- a [documentation rule](https://github.com/pattern-lab/patternlab-php/blob/dev/core/lib/PatternLab/PatternData/Rules/DocumentationRule.php) for reading markdown files with YAML front-matter. This info is going to be displayed on the style guide and code view modal.
- a [starter kit class](https://github.com/pattern-lab/patternlab-php/blob/dev/core/lib/PatternLab/StarterKit.php) for downloading bundles of patterns & assets from GitHub similar to Bower. 
- a [snapshot class](https://github.com/pattern-lab/patternlab-php/blob/dev/core/lib/PatternLab/Snapshot.php) for copying the current state of `public/`. Brad is doing this by hand for his food bank project but maybe it'll be useful to other folks too.
- pattern data can be defined in JSON or YAML. since YAML was added for the doc support it seemed to make sense to open it up to be used everywhere.

I'm sure there are a few more things hidden away but those are the main highlights outside of the _huge_ reorganization of the PHP edition. It was definitely needed.

There is still more to be done before I think I can feel comfortable coming back to the spec. I'm hoping to get a new release out in the next few weeks. It will include a bit of a rewrite with how we're handling passing data around the front-end as well as re-building the "viewer." Expect more use of JSON. The header and footer will be moved to `_meta` and I think the PHP edition will pick up Handlebars as another pattern engine.

I'm also currently trying to sketch out where and how we can drop in "plug-ins" throughout out the system. Pattern states and KSS are my guinea pigs (btw, if you see "plugin" folders in `dev` don't expect that organization to stay). The plug-in structure shouldn't make the next release. This is just a heads up that it's out there. This will be something that will have to span the back-end and front-end.

If you have questions or issues let me know.

/cc @bradfrost

**Comment by benedfit** [comment]
From my perspective the only thing that I know for a fact will be different is the way I want to handle starter kits. Rather than being a case of pointing at a git repo, starter kits will be handle via NuGet packages in the .NET version, so it would be cool if the spec could flex to allow ports specific handling of starter kits

**Comment by dmolsen** [comment]
@benedfit -

I'll work in that flexibility.
