### ISSUE TITLE
Vote: Add Brad Frost as a Voting Member

### ISSUE THREAD

**Issue by dmolsen** [pattern-lab/the-spec#12]
Voting membership in PL-PIG is currently limited to Core implementations of Pattern Lab. One representative from each implementation gets a vote. To provide a different perspective I'm proposing that Brad Frost be added as a voting member. 

This vote will close at noon eastern on June 13, 2016 or once both the PHP and Node representatives have voted.

/cc @pattern-lab/voting-members

**Comment by bradfrost** [comment]
VETO EVERYTHING.

**Comment by dmolsen** [comment]
@bradfrost -

Please submit a PR to the [rules](https://github.com/pattern-lab/the-spec/blob/draft/PL-PIG.md) if you'd like veto power ;)

**Comment by bradfrost** [comment]
I VETO THE RULES. 

(planning on looking at this today)

**Comment by bmuenzenmeyer** [comment]
:+1: 

I am @bmuenzenmeyer, and I approve this message

**Comment by dmolsen** [comment]
Realized the thumbs up on an individual message doesn't cause responses to pop up in "notifications" so adding my official 👍 . Welcome to PL-PIG, @bradfrost. I'll add a section to the membership doc listing the voting members and their reps where applicable.
