### ISSUE TITLE
Discussion and Vote: Pattern Info Toggle Persistence / Default

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/the-spec#15]
As a design systems creator, I want Pattern Lab's Pattern Info section to default open so that my consumers can see descriptions, annotations, code, and lineage alongside the patterns themselves.

_or maybe_

As a user of Pattern Lab, I want my Pattern Info choice remembered across clicks and sessions so that I don't have to constantly toggle Pattern Info back on.

---

As [discussed in these comments yesterday](https://github.com/pattern-lab/styleguidekit-assets-default/issues/11#issuecomment-222790907), it'd be nice if patternInfo toggle state was configurable open/close on launch, or persisted per user .

The timeline for this feature is not critical for 2.0.0 release

Tagging core and shared assets because configuration is managed at core level and then is controlled on the frontend. 

This vote will close at noon central on June 15th, 2016 or once both the PHP and Node representatives have voted.

/cc @pattern-lab/voting-members

**Comment by dmolsen** [comment]
I see the value but trying to nail down the mechanics of this. 

### System Input

The user sets this by updating a `defaultShowPatternInfo` option in the config. It should be formatted as a boolean. By default the config option should be set to `false`.

### System Output

It should be passed to the viewer via a config option. Haven't checked this in code but... When the viewer receives an `updatePath` event it should:
- check to see if a cookie is set. if not check to see if defaultShowPatternInfo is `true`. show if it is. if the cookie is set...
- check a cookie to see if showPatternInfo is `true`. show if it is.

On clicks of pattern info update the cookie (_right now it's just a var in JS_).

### Questions
- Does `defaultShowPatternInfo` toggle the pop-up modal too or just the `viewall-*` pages?

**Comment by bmuenzenmeyer** [comment]
What you describe sounds correct from a pseudo-code standpoint as far as I can tell.

> Does defaultShowPatternInfo toggle the pop-up modal too or just the viewall-\* pages?

I would think only `viewall-*` pages for now. In my opinion, this option's intent is to let you browse Pattern Lab, taking in the patterns as well as their usage, relationships, code, etc. along the way. But ultimately, it's an experience best suited for perusal of whole sections.

My own question:
- Does `updatePath` get called on load? Or would something need to built special to initialize the state based on the config entry, other than that event? Forgive my ignorance on the internals of the UI.

**Comment by dmolsen** [comment]
I think the event I would hook into would actually be `pageLoad`. That goes from pattern to viewer and fires for every path loaded inside the iFrame. `updatePath` goes from viewer to pattern on a click in the viewer. Got those mixed up.

**Comment by dmolsen** [comment]
With the `viewall-*` question answered and people signing off on the naming convention I'm a:

👍

**Comment by bmuenzenmeyer** [comment]
:+1:

**Comment by dmolsen** [comment]
This has been implemented and will be hitting various `dev` branches on the repos this afternoon.
