### ISSUE TITLE
Discussion: How to Track Implemented Progress Against Specification

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/the-spec#18]
It would be nice if we could come up with a process and single place to track spec compliance across implementations.

For example, we just voted to pass [Pattern Info Toggle Persistence / Default](https://github.com/pattern-lab/the-spec/issues/15), but how will we track development against it. 

Some ideas:
- Does it get tagged as vote passed but not closed until all core implementations have addressed it? 
- Do we build a big feature table ala caniuse to track progress?
- Do core implementations open issues referencing the closed measure, and then can track it independently?

**Comment by dmolsen** [comment]
> Do core implementations open issues referencing the closed measure, and then can track it independently?

Yes. And an implementation to `styleguidekit-assets-default` should either be done in a way that won't break if a Core implementation hasn't implemented the feature or have a major version bump.

**Comment by bmuenzenmeyer** [comment]
Works for me, thanks Dave.
Closing.
