### ISSUE TITLE
Change patternBreadcrumb to an Object Instead of a String

### ISSUE THREAD

**Issue by dmolsen** [pattern-lab/the-spec#19]
A user would like to easily modify the breadcrumb separator.

---

To give front-end developers more control I'd like to switch the `patternBreadcrumb` output option from a string to an object. This would allow customization without a configuration option or us mucking with Core.
## System Output

The `patternBreadcrumb` output would look like:

```
"patternBreadcrumb": {
    "patternType": "atoms",
    "patternSubtype":"global"
}
```

For patterns without a subtype it'd look like:

```
"patternBreadcrumb": {
    "patternType": "templates"
}
```

The timeline for this feature is essentially now. I think this is a small change that we can each quickly implement.

Tagging **frontend/shared-assets** because this issue affects the viewer. 

This vote will close at **9PM EST** on **June 26** or once the issue gets two thumbs up or two thumbs down.

/cc @pattern-lab/voting-members

**Comment by dmolsen** [comment]
👍

**Comment by bmuenzenmeyer** [comment]
Sounds reasonable.

:+1: 

P.S. Are the `feature-panels` branches going through to `dev` and `master` sometime soon?

**Comment by dmolsen** [comment]
The idea was to finish annotations before merging `feature-panels` with `dev` and then `master`. That's on @bradfrost at the moment to finish up a look for annotations. Then I'll try to come through and clean-up the code.

I have this implemented in `feature-panels` but haven't pushed it. Let me know when I can do that.

**Comment by bradfrost** [comment]
> The idea was to finish annotations before merging feature-panels with dev and then master. That's on @bradfrost at the moment to finish up a look for annotations. 

@dmolsen @bmuenzenmeyer Yep I'm on it.

**Comment by dmolsen** [comment]
This has been implemented and will be hitting various `dev` branches on the repos this afternoon.
