### ISSUE TITLE
Consolidate or Define usage of the words General/Common/Core

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/the-spec#2]
Dave, in general the ToC is great and covers a lot of ground, so please don't consider my feedback a reflection on total quality :)

I find the terms General, Common, and Core to be far too similar, to the point that they become useless qualifiers. They all speak to a "baseline" or "foundational" element I think. The absence headings that are opposite of these qualifiers makes them flatter.

For example:

```
3. Common Infrastructure
  3.1. Core Technologies
  ...
  3.2. Core Organization
```

There is no `3.3` which could possibly define derivatives of the core.

Dropping "Core" from `3.1.` and `3.2` or promoting it up to `3. Core Infrastructure` seems to make sense to me.

Thoughts? Trying not to be picky - its the English major in me :)

**Comment by dmolsen** [comment]
Dropped both "core" and "common" and reorganized it a little. Technologies (not terribly happy with the name) is now separate from File System.
