### ISSUE TITLE
Discussion & Vote: Developing an Acid Test StarterKit

### ISSUE THREAD

**Issue by dmolsen** [pattern-lab/the-spec#23]
I need to check if my changes to core affect output in an unexpected way. I also need to make sure my changes meet the needs of spec.

---

We have no good way to ensure that Node and PHP are developing towards spec or if we are in compliance. We use the demo but it doesn't address all of the various test cases we need to develop to properly define the boundaries of the spec.

An [Acid Test](http://www.acidtests.org) StarterKit could give us a common base to use for testing. If we roll in visual regression testing we can quickly see where our changes break the expected output. This idea is based on the initial work of James Nash so full credit to him for the idea.

The timeline for this feature is sooner rather than later. At a minimum we can roll out the StarterKit and tack on visual regression testing at some point in the future. I'm willing to put together the patterns for the StarterKit as PHP is closest to being spec-compliant.

Tagging process-enhancement because this is all about making sure we work better together across platforms.

This vote will close at 10EST on July 22nd or once two voting members have given the yay or nay.

/cc @pattern-lab/voting-members

**Comment by dmolsen** [comment]
Easy vote for me 👍

**Comment by bmuenzenmeyer** [comment]
I love this idea, thanks again to @james-nash for the idea. I had started a pattern tree that would test some data-inheritance scenarios for a possible bug, so am excited to have a shared reference to document expected output.

:+1:
