### ISSUE TITLE
Including Patterns in Header & Footer

### ISSUE THREAD

**Issue by dmolsen** [pattern-lab/the-spec#24]
A user wants to include an atom or other pattern as part of their global header and/or footer.

---

I believe this is an issue that only affects PL/PHP. I wanted to bring it up as a spec change just in case. This way we'll know how each port renders the header and footer. PL/PHP renders the header and footer as strings so it can't load patterns/partials. This was done for performance reasons. I will try to find a way to minimize the impact of using the full pattern loader over and over again for really simple content.
## System Output

When rendered a full pattern's header and footer will include content referenced by includes.
## Extra

The timeline for this feature is near term just because I think it's an easy change.

Tagging core and spec-question because it'll be implemented in core and i'm unsure if PHP is the only one not doing this.

This vote will close at **12PM** on **July 25** or once two voting members have voted yay or nay.

/cc @pattern-lab/voting-members

**Comment by dmolsen** [comment]
👍

**Comment by bmuenzenmeyer** [comment]
I'd need to try it in PL/Node - but I think it won't work either - although all the pieces are in place.

Makes sense to me - as long as people understand the ramifications of adding something to every pattern.

:+1:

**Comment by alkaithil** [comment]
Hi, I'm trying to include a pattern in the footer and it seems it's not working. I stumbled into this page and it seems it's not yet implemented. Can someone help me with this issue? Is it going to be implemented any time soon? Any other workarounds I could use? Thanks!

**Comment by bmuenzenmeyer** [comment]
Hello @alkaithil which tool are you using?

**Comment by alkaithil** [comment]
Patternlabs PHP. I know it's marked as solved but I can't make it work.

**Comment by bmuenzenmeyer** [comment]
Hmm... I tried finding other issues or PRs to this respect too, but with no
luck. Could you please try in the https://gitter.im/pattern-lab/php chat
channel? Perhaps other PHP users have a workaround. I really only have the
bandwidth to support the Node version right now, unfortunately.
