### ISSUE TITLE
Discussion & Vote: Hiding Folders of Patterns in the Nav

### ISSUE THREAD

**Issue by dmolsen** [pattern-lab/the-spec#27]
A user wants remove the subtype `atoms > global` from the nav.

---

This is to formalize the request and implementation made in pattern-lab/patternlab-node#414 by @e2tha-e. A user should be able to add an underscore to a subtype to hide it in the nav.

**Note:** I would argue that this feature should be available to types _in addition_ to subtypes. I'm unsure if @e2tha-e's feature affects types or not. We don't currently support documentation `.md` files for types and we'd need that implemented too. For now subtypes are good enough.
## System Input

A pattern subtype has an underscore. For example, `atoms/_global`. 
## System Output

The patterns are processed so they are available to be included in other patterns. They are **not** visible in the nav.
## Spec Info

The timeline for this feature is **not at all critical.** Tagging **spec-enhancement** because this would expand on existing functionality for patterns. This vote will pass when two voting members say yay or when two voting members say nay.

/cc @pattern-lab/voting-members

**Comment by dmolsen** [comment]
:+1: easy one for me

**Comment by bramsmulders** [comment]
👍

**Comment by bmuenzenmeyer** [comment]
:+1:  vote passed with Dave and I's vote

**Comment by bradfrost** [comment]
👍

**Comment by e2tha-e** [comment]
👍

**Comment by dmolsen** [comment]
@bmuenzenmeyer -

I think we need to say "vote passed" when either of us casts the deciding vote ;)

**Comment by bmuenzenmeyer** [comment]
amended :smile:
