### ISSUE TITLE
Discussion & Vote: Pattern Type Documentation

### ISSUE THREAD

**Issue by dmolsen** [pattern-lab/the-spec#28]
A user wants to document what an overarching pattern type is for or use documentation attributes like title, hidden, or order.

---

The UI doesn't currently support showing pattern type documentation but it might be good to make all of the documentation and configuration options available to a pattern type in addition to patterns and pattern subtypes.
## System Input

A user creates a `.md` file in the appropriate format at the same level as the pattern types. It should be read as documentation for the related pattern. For example:

```
source/
  atoms/
  atoms.md
  molecules/
  organisms/
```

Would mean that `atoms` had documentation and/or configuration info.
## System Output

Similar to the set-up of pattern subtypes for the "view all" views. Would need to pass the following attributes to the "view all" view so it could be rendered:
- `patternName`
- `patternLink`
- `patternPartial`
- `patternDesc`
- `patternSectionType`

The `patternLink` would match what is passed for the nav. I will need to add this check and output partial to the `styleguidekit-[templatelang]-default` repos.

Otherwise the other features like hidden or order should be honored. State would be ignored.
## Spec Info

The timeline for this feature is **not critical**. Tagging **spec-enhancement** because this is an expansion of existing features. This vote will close at **10P Eastern** on **August 11** or once two of the voting members have voted yay or two of the voting members have voted nay.

/cc @pattern-lab/voting-members

**Comment by bmuenzenmeyer** [comment]
I am in favor of this change. 

:+1:

**Comment by bradfrost** [comment]
As someone who has to re-explain UI component hierarchy over and over again, I'm in favor of this.

👍

**Comment by dmolsen** [comment]
👍 

Vote passed with Brad's vote.
