### ISSUE TITLE
Improving pattern linking to include View Alls

### ISSUE THREAD

**Issue by EvanLovely** [pattern-lab/the-spec#35]
Currently, the [`link` variable for linking between patterns](https://github.com/pattern-lab/website/blob/master/docs/data-link-variable.md) only supports linking to a single pattern, this adds the ability to link to the View Alls such as "Atoms > View All" or "Atoms > Forms > View All".

This has been added in PHP [`v2.8.5`](https://github.com/pattern-lab/patternlab-php-core/releases/tag/v2.8.5) from [this PR](https://github.com/pattern-lab/patternlab-php-core/pull/140).

/cc @pattern-lab/voting-members

**Comment by EvanLovely** [comment]
This is an easy vote for me 😉 : 👍

**Comment by EvanLovely** [comment]
From @bmuenzenmeyer : 
> Node supports patterns only. It would probably be pretty simple to implement, however. This would be a spec enhancement, IMO.

From @bradfrost : 
> I like this idea, especially keeping in mind the efforts to evolve PL into more of a style guide tool as well. Would be helpful to be able to link to a cluster of patterns.

**Comment by bmuenzenmeyer** [comment]
A little after the fact... but I 👍

**Comment by bmuenzenmeyer** [comment]
vote passes
