### ISSUE TITLE
Addressing a Paradox in the Spec

### ISSUE THREAD

**Issue by dmolsen** [pattern-lab/the-spec#4]
We have a paradox in the spec.

Spec Item 4.1: There should be no hard coding of atomic design into Pattern Lab builders. Basically, people should be able to name directories and patterns however they want and have things just work.

Spec Item 4.8.3.2: The user-modifiable header and footer should live under 00-atoms/00-meta.

The latter, 4.8.3.2, will be a MUST when I get to writing it up. Obviously, it goes against 4.1. To address the paradox I'm proposing that we instead use a `_meta` directory to hold these items. It'd be at the root with `_patterns/` and `_data/`. I [wrote up this option](https://github.com/pattern-lab/patternlab-php/issues/64#issuecomment-29476376) and several others in an early PL issue. I think it's the best balance between flexibility and author control.

Sound ok? Better solutions?

/cc @bradfrost @pattern-lab/port-maintainers

**Comment by benedfit** [comment]
Seems like a sensible approach. Could you ever foresee a need for these to be processed by Mustache? As I still feel that them being .html files and using {% %} for element injection is at odds with the rest of the code base

**Comment by dmolsen** [comment]
@benedfit -

I think you're confusing two separate things. There is the system header and footer _includes_ which are `.html` files. That's where we need to stick those things that are required for PL to work (annotation JS, overall styles). Those things currently sit in `core/templates/pattern-header-footer/`. 

What I'm talking about is the user-editable pattern header and footer that sit in `source/_patterns/00-atoms/00-meta/`. These files do get processed by Mustache after the includes are injected directly by PHP.

As for your other concern I guess we can just shove more info into `d` (the var that holds the vast majority of the data) as that's passed to Mustache when the header and footer are processed. I can add the includes as well as the pattern-specific attributes.

**Comment by benedfit** [comment]
Apologies, my bad, I keep doing that :)

**Comment by dmolsen** [comment]
@benedfit -

Hey, it made me realize there was a solution to the other issue ;)

**Comment by bmuenzenmeyer** [comment]
I'd also mention that http://patternlab.io/ is full of inferences that PL is for atomic web design.

Prominent examples include the tagline and the http://patternlab.io/about.html page

**Comment by dmolsen** [comment]
@bmuenzenmeyer -

I've updated the spec so that it's clearer. What that section will cover is the fact that Pattern Lab ports must not be hardcoded to only work with directories named "atoms," "molecules," "organisms," "templates," and "pages." If someone doesn't like that as an organizational model they should be able to rename directories as they please. So, rather than "organisms" maybe they prefer "partials?" They can change that. They have to update any of their pattern partials that referenced "organisms" but, hey, whatever floats their boat. They should also be able to add to or remove any of those top-level directories. 

By default we ship a demo that is based on the atomic design naming convention from the website but atomic design is more about little bits of mark-up and groups of mark-up than it is those exact names. Let's err on the side of allowing flexibility to the pattern author even if it's not completely obvious the tools can be used that way.

**Comment by bmuenzenmeyer** [comment]
Thanks for the thoughts Dave

**Comment by dmolsen** [comment]
@bradfrost -

If you don't have an opinion or an objection I'm going to move that stuff to a `_meta` folder. I can create migrations in the PHP version that can handle the auto-migration of that for folks who upgrade. I'll wait until Tuesday for a response and then make the switch if you don't chime in.

**Comment by bradfrost** [comment]
@dmolsen, opinion on what? Where the `head` and `foot` live?

**Comment by dmolsen** [comment]
@bradfrost -

Yes, the head and foot that currently live in `source/_patterns/00-atoms/00-meta`. I'm asking if I can move them to `source/_meta` to avoid conflicts in spec.

**Comment by bradfrost** [comment]
Ah, ok. Yeah, I mean if it makes it a lot more portable, then do it. Ideally, we don't want to have a shit ton of folders within `source`, but again if it makes things a lot easier to manage and port, then definitely go for it.

**Comment by benedfit** [comment]
@dmolsen - Do you plan to make the files in `_meta` always Mustache driven, or dependent on the active pattern engine? I don't have issues with either way, just thinking ahead

**Comment by dmolsen** [comment]
@benedfit -

Active pattern engine. Anything in `source/` is going to be scoped to the pattern engine and not the default Mustache engine.
