### ISSUE TITLE
Highlighting future specifications 

### ISSUE THREAD

**Issue by benedfit** [pattern-lab/the-spec#7]
@dmolsen - Can you list out the specs that the current PHP version won't support until the next release? 

This will help with checking that the ports are all currently in line

**Comment by dmolsen** [comment]
@benedfit -

I updated the spec. Items with a single asterisk are currently in `dev` so will definitely ship. Items with a double-asterisk should ship but I have work to do.

**Comment by benedfit** [comment]
Thanks
