### ISSUE TITLE
Can we specify camelCase or underscore_case for .json?

### ISSUE THREAD

**Issue by benedfit** [pattern-lab/the-spec#9]
For the next release of the .NET version in enabling support for writing templates in Razor syntax. Unfortunately the Razor equivalent of `{{ author.first-name }}`, `@Model.author.first-name` causes a compilation error as .NET interprets the hyphen as a minus sign.

I can fix this by tweaking the sample json to use camelCase or underscore_case, but it would be cool if we could all agree which, switch, and let all users know

**Comment by benedfit** [comment]
FWIW, I'm gonna try as hard as I can on my end to handle this with parsing, but every little helps :)

**Comment by bmuenzenmeyer** [comment]
To me this is one of those details that should be left to the port - it's a language nuance that any spec cannot possibly define for all circumstances. When I started PL-node I deviated from the PL-PHP algorithm heavily - using the _final output_ as the only measure of success.

I am not saying that we shouldn't attempt to use common input wherever possible, but that we shouldn't sweat the small stuff. Interested to hear what @dmolsen thinks.

**Comment by dmolsen** [comment]
Is this an issue for your templates or for the pattern lab engine itself? If the former do what you want case-wise. The demo data, patterns and assets should probably not be ported. Better to do something much simpler as a Razor-based start point.

**Comment by benedfit** [comment]
It's simply an issue from a pattern template perspective; .NET can parse the current json no problem, it's just that Razor will never allow any properties with a hyphen in the name to be output. While I agree that this is a language nuance, and one that I'll try my darnedest to fix, it would be cool if I could get away with having a differently cased demo data.json for the Mustache and Razor starter kits seeing as what's there is so useable bar this one edge case.

Upon reflection, maybe this isn't an issue for the spec, and more of a case of us all agreeing on a preferred json style convention, and applying changes, if needed, to the PHP repo

**Comment by dmolsen** [comment]
@benedfit -

Either I wasn't clear or I'm not understanding your issue. Let's say we have a starter kit for the Mustache-based demo. It'll have the following in it:
- _data/
- _patterns/
- css/
- fonts/
- etc…

A starter kit for the Razor-based demo would have:
- _data/
- _patterns/
- css/
- fonts/
- etc…

Basically the Razor demo is entirely separate from the Mustache one. So do whatever you need to do in the Razor-based starter kit to fit the needs of that engine. Rename the keys… whatever. When I say that the demo shouldn't be ported I'm merely referring to the fact that the patterns and their associated styles aren't bulletproof and should not be seen as a starting point for projects. [See Brad's comments on this](https://github.com/pattern-lab/patternlab-php/blob/master/core/source/css/style.scss#L15-L16) . I think it's a bit of a waste of time to migrate the demo but that's entirely up to you. I wouldn't do it for Twig.

**Comment by benedfit** [comment]
@dmolsen - while I agree it's not a big deal for me to have differently cased json files in each of my starter kits, I'm always looking to use files directly from the PHP version if I can. And while a switch to a more Razor friendly case doesn't completely eradicate my issue, it'll hopefully soften the blow as users of the starter kits would be more likely to follow suit with the case already in use

Like I said, this is actually less of a spec issue and more of a request to change the current style convention.

**Comment by dmolsen** [comment]
@benedfit -

The current style isn't going to change. I'm not going to start making changes to suit pattern engines that aren't part of spec which is ultimately what you're asking even if you don't think it's a spec issue. Starter Kits should and will be scoped to engines as opposed to platforms. If the argument is someone will use the .NET port, start with a Mustache starter kit using the wrong naming convention, make significant changes, and then want to switch to Razor and have to rename their data… that seems unlikely to me and just something they'd have to deal with.

The demo will be spun out of the PHP version into its own repo and use the starter kit functionality in `dev` to pull it down. This way all three ports can use the same base starter kit and should be less for you to update/deliver as part of your initial install.

I also hope that we (Brad + I) get to the point where we have a much better starting point that doesn't contain all of the cruft of styles and patterns that Brad doesn't want duplicated. That might also help limit bad habits from forming.
